version: 2.1

executors:
  executor-ubuntu:
    machine:
      image: ubuntu-2004:202111-01

jobs:
  test_app:
    executor: executor-ubuntu
    steps:
      - checkout
      - run:
          name: "Cambiar version de Python"
          command: pyenv global 3.9.7
      - run:
          name: Instalar poetry
          command: pip install poetry
      - run:
          name: Instalar dependencias
          command: poetry install 
      - run:
          name: Run tests
          command: docker run -e ETCD_PORT=${ETCD_PORT} LOG_FILE=${LOG_FILE} LOG_LEVEL=${LOG_LEVEL} -t -v `pwd`:/app/test joaquingv12/car_workshop-maximizer

workflows:
  testear_app:
    jobs:
      - test_app