version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/python:3.8

jobs:
  test_app:
    executor: my-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Run tests
          command: docker run -t -v `pwd`:/app/test joaquingv12/car_workshop-maximizer

workflows:
  testear_app:
    jobs:
      - test_app