name: Actualizar docker en DockerHub
on: 
  push:
    branches:
      - main
    pull_requests:
      branches:
        - main

jobs:
  actualiza_docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: latest