name: Actualizar docker en DockerHub
on: 
  push:
    paths:
      - 'src/**'
      - 'test/**'
    branches:
      - main
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'
    branches:
      - main
jobs:
  actualiza_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build and push to docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }} 
          tags: latest